### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by TimSchmeier** [pishen/annoy4s#1]
Hi Pishen,

When compiling the package locally running `sbt test` results in an unresolved dependency error.

`[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.pathikrit#better-files_2.10;2.16.0: not found`

I tried using better-files 2.14.0 but compilation still failed. I'm using scala version 2.10.4.

Any help would be appreciated.
Tim

**Comment by pishen** [comment]
Is the error like this?
```
[error] .../annoy4s/src/main/scala/annoy4s/Annoy.scala:88: value printLines is not a member of better.files.File
[error]       (File(outputDir) / "ids").printLines(inputLines.map(_.split(" ").head))
[error]                                 ^
[error] .../annoy4s/src/main/scala/annoy4s/Annoy.scala:111: value lineIterator is not a member of better.files.File
[error]     val idToIndex = ids.lineIterator.toSeq.map(_.toInt).zipWithIndex.toMap
[error]                         ^
[error] .../annoy4s/src/main/scala/annoy4s/Annoy.scala:112: value lineIterator is not a member of better.files.File
[error]     val indexToId = ids.lineIterator.toSeq.map(_.toInt)
[error]                         ^
[error] three errors found
```
Seems that I used some functions that's only available in better-files 2.16.0. We may ask @pathikrit to provide a Scala 2.10 version for better-files 2.16.0, or see if we can avoid using these functions.

**Comment by pishen** [comment]
@TimSchmeier I've committed a branch for Scala 2.10, could you try this one to see if there's any problem?
https://github.com/pishen/annoy4s/tree/scala_2.10

**Comment by TimSchmeier** [comment]
The new branch still fails during `sbt test`. The previous error was like I posted, I did not see the 3 errors you posted. I logged the stdout and attached it below.

[test_log.txt](https://github.com/pishen/annoy4s/files/643833/test_log.txt)

**Comment by pishen** [comment]
@TimSchmeier Which Java version did you use? better-files requires Java 8 to function properly.

**Comment by TimSchmeier** [comment]
That was it, updating my java and using the scala_2.10 branch addresses the issue. Thank you for the help.
